export const UK_PROFESSIONS = [
  'Bricklayer',
  'Carpenter & Joiner',
  'Plasterer',
  'Electrician',
  'Plumber',
  'Painter & Decorator',
  'Roofer',
  'Scaffolder',
  'Steel Fixer / Rebar',
  'Groundworker',
  'Labourer',
  'Plant Operator (Forklift)',
  'Plant Operator (Excavator)',
  'Plant Operator (Telehandler)',
  'Crane Operator',
  'HVAC Engineer',
  'Gas Engineer',
  'Tiler (Floor)',
  'Tiler (Wall & Floor)',
  'Stonemason',
  'Dry Liner',
  'Insulation Installer',
  'Glazier',
  'Welder',
  'Demolition Operative',
  'Surveyor',
  'Site Manager',
  'Project Manager',
  'Health & Safety Officer',
  'QS / Quantity Surveyor',
  'Civil Engineer',
  'Structural Engineer',
  'Architect',
  'Floorer',
  'Landscaper',
  'Drainage Engineer',
  'Waterproofer',
  'Sprinkler Fitter',
  'Fire Door Installer',
  'Cladding Installer',
  'Asbestos Removal Operative',
  'Traffic Marshall',
  'Security Officer',
  'Cleaner (Construction)',
  'Other',
] as const

export type Profession = (typeof UK_PROFESSIONS)[number]
